/* auto-generated by NAPI-RS */
/* eslint-disable */

/** 人设轮转：soft → tsundere → derriere → cool → soft，返回新风格。 */
export declare function cyclePersona(): string

/** P0 骨架自述串（smoke 用）。 */
export declare function engineInfo(): string

/** JS 侧可选参数（camelCase 字段）。 */
export interface EngineOptsJs {
  personaStyle?: string
  intensity?: string
  customFallback?: string
  decorateFallback?: boolean
}

/** 引擎统计（含规则版本与规则数）。 */
export declare function getStats(): StatsJs

/** 规则热加载：`builtin` / `file:<路径>` / 原始 DSL 文本，返回新规则版本。 */
export declare function loadRules(source: string): string

/** 直接加载规则 DSL 文本（浏览器端 file: 由调用方先取文本）。 */
export declare function loadRulesText(text: string): string

/** 统计对象（path 固定 native，wasm 壳镜像为 wasm）。 */
export interface StatsJs {
  path: string
  rulesVersion: string
  persona: string
  ruleCount: number
}

/** MarkdownLint 消息（结构化兜底保留前缀/详情）。 */
export declare function transformMarkdownlint(msg: string, opts?: EngineOptsJs | undefined | null, code?: string | undefined | null): string

/** 消息主入口。 */
export declare function transformMessage(msg: string, opts?: EngineOptsJs | undefined | null): string

/** PyLint 消息（结构化兜底保留规则码前缀）。 */
export declare function transformPylint(msg: string, opts?: EngineOptsJs | undefined | null, code?: string | undefined | null): string

/** 颤音彩蛋：命中关键词返回彩蛋文案，否则空串。 */
export declare function transformWhimper(input: string, opts?: EngineOptsJs | undefined | null): string
