#!/usr/bin/env node
// 生成 src/rules.generated.ts：
//   基准1: cpptools 1.34.4 原文 <-> kawaii 文案（逐索引配对）
//   基准2: cpptools 1.19.7 原文 <-> 同索引 kawaii 文案（占位符序列一致才采纳）
// 规则以“原文文本”为键（不依赖索引），因此对任意版本 cpptools 的
// messages.json 都可就地直接 replace；未命中条目由运行时正则兜底装饰。
// 用法: node scripts/build-rules.mjs
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BASE_DIR = path.join(ROOT, 'assets', 'baseline');
const KAWAII_PATH = path.join(ROOT, 'assets', 'reference', 'messages.json');
const OUT_PATH = path.join(ROOT, 'src', 'rules.generated.ts');

const PRIMARY = '1.34.4';
const SECONDARY = '1.19.7';
const COVERAGE = ['1.34.4', '1.19.7', '1.35.3'];

// 占位符形态：%% | %[方括号] | %字母族+数字下标（用 RegExp 构造器避免字面量转义歧义）
const TOKEN_RE = new RegExp('%%|%\\[[^\\]]*\\]|%[A-Za-z]+\\d*', 'g');

const tokens = (s) => s.match(TOKEN_RE) ?? [];
const seqKey = (arr) => arr.join('\u0001');
const multiKey = (arr) => [...arr].sort().join('\u0001');

function loadJson(p) {
  if (!fs.existsSync(p)) {
    console.error(`缺少文件: ${p}\n先运行: npm run fetch-baseline`);
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function assertArray(name, v) {
  if (!Array.isArray(v)) {
    console.error(`${name} 不是 JSON 数组`);
    process.exit(1);
  }
}

const kawaii = loadJson(KAWAII_PATH);
assertArray('kawaii 文案', kawaii);
const primary = loadJson(path.join(BASE_DIR, `orig-${PRIMARY}.json`));
assertArray(`orig-${PRIMARY}`, primary);

if (primary.length !== kawaii.length) {
  console.error(`长度不一致: orig-${PRIMARY}=${primary.length}, kawaii=${kawaii.length}（基准版本不匹配？）`);
  process.exit(1);
}

let nullMismatch = 0;
for (let i = 0; i < kawaii.length; i++) {
  if ((kawaii[i] === null) !== (primary[i] === null)) nullMismatch++;
}
if (nullMismatch > 0) {
  console.error(`null 位置不一致 ${nullMismatch} 处，基准与文案不配对，拒绝生成`);
  process.exit(1);
}

// key -> Set<variant>
const rules = new Map();
let identity = 0;
let addedPrimary = 0;
let skipOrderSwap = 0;
let skipPlaceholder = 0;

function tryAdd(orig, cute, tag) {
  const tOrig = tokens(orig);
  const tCute = tokens(cute);
  if (seqKey(tOrig) !== seqKey(tCute)) {
    if (multiKey(tOrig) === multiKey(tCute)) {
      skipOrderSwap++;
    } else {
      skipPlaceholder++;
    }
    return false;
  }
  let set = rules.get(orig);
  if (!set) { set = new Set(); rules.set(orig, set); }
  const before = set.size;
  set.add(cute);
  if (set.size > before) addedPrimary += (tag === 'p' ? 1 : 0);
  return set.size > before;
}

for (let i = 0; i < primary.length; i++) {
  const o = primary[i];
  const k = kawaii[i];
  if (o === null || k === null) continue;
  if (o === k) { identity++; continue; }
  tryAdd(o, k, 'p');
}

let addedSecondary = 0;
const secondaryPath = path.join(BASE_DIR, `orig-${SECONDARY}.json`);
if (fs.existsSync(secondaryPath)) {
  const secondary = loadJson(secondaryPath);
  assertArray(`orig-${SECONDARY}`, secondary);
  const n = Math.min(secondary.length, kawaii.length);
  for (let i = 0; i < n; i++) {
    const o = secondary[i];
    const k = kawaii[i];
    if (o === null || k === null) continue;
    if (o === primary[i]) continue; // 基准1 已覆盖
    if (o === k) continue;
    const tOrig = tokens(o);
    const tCute = tokens(k);
    if (seqKey(tOrig) !== seqKey(tCute)) continue;
    let set = rules.get(o);
    if (!set) { set = new Set(); rules.set(o, set); }
    const before = set.size;
    set.add(k);
    if (set.size > before) addedSecondary++;
  }
}

// 重复原文（多变体）统计
let dupGroups = 0;
let dupMultiVariant = 0;
for (const [, v] of rules) {
  if (v.size >= 1) {
    dupGroups++;
    if (v.size > 1) dupMultiVariant++;
  }
}

// 生成 TS
const obj = {};
for (const [k, v] of [...rules.entries()].sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
  obj[k] = [...v];
}
const canonical = JSON.stringify(obj);
const version = 'sha256:' + crypto.createHash('sha256').update(canonical).digest('hex').slice(0, 16);

const lines = [];
lines.push('// AUTO-GENERATED by scripts/build-rules.mjs —— 不要手改。');
lines.push(`// 基准: cpptools ${PRIMARY} + ${SECONDARY} (zh-cn messages.json)`);
lines.push('// 文案: Gary-0925/kawaii-vscode-cpptools (MIT, 见 assets/reference/NOTICE)');
lines.push(`export const RULES_VERSION = ${JSON.stringify(version)};`);
lines.push('export const RULES: Record<string, string[]> = {');
for (const [k, v] of Object.entries(obj)) {
  lines.push(`  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
}
lines.push('};');
lines.push('');
fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, lines.join('\n'));

// 覆盖率报告
const totalBytes = fs.statSync(OUT_PATH).size;
console.log(`生成 ${path.relative(ROOT, OUT_PATH)} (${(totalBytes / 1024).toFixed(0)} KB, RULES_VERSION=${version})`);
console.log(`基准1 ${PRIMARY}: 规则键 ${rules.size}, 保留原文(identity) ${identity}, 占位符换序跳过 ${skipOrderSwap}, 占位符不一致跳过 ${skipPlaceholder}`);
console.log(`基准2 ${SECONDARY}: 新增键 ${addedSecondary}, 多变体键 ${dupMultiVariant}`);

console.log('\n覆盖率（按原文文本精确命中规则表的非 null 条目占比）:');
for (const ver of COVERAGE) {
  const p = path.join(BASE_DIR, `orig-${ver}.json`);
  if (!fs.existsSync(p)) { console.log(`  ${ver}: 缺基线，跳过`); continue; }
  const arr = loadJson(p);
  let nonNull = 0, hit = 0;
  for (const e of arr) {
    if (e === null) continue;
    nonNull++;
    if (rules.has(e)) hit++;
  }
  console.log(`  ${ver}: ${hit}/${nonNull} = ${(hit / nonNull * 100).toFixed(2)}%`);
}
